# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seg_xfer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='seg_xfer.proto',
  package='seg_xfer',
  syntax='proto3',
  serialized_pb=_b('\n\x0eseg_xfer.proto\x12\x08seg_xfer\"\xc4\x01\n\tPacketMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06src_ip\x18\x02 \x01(\r\x12\x10\n\x08src_port\x18\x03 \x01(\r\x12\x0e\n\x06\x64st_ip\x18\x04 \x01(\r\x12\x10\n\x08\x64st_port\x18\x05 \x01(\r\x12\x11\n\ttcp_flags\x18\x06 \x01(\r\x12\r\n\x05seqno\x18\x07 \x01(\r\x12\r\n\x05\x61\x63kno\x18\x08 \x01(\r\x12\x0f\n\x07payload\x18\t \x01(\x0c\x12\r\n\x05\x64size\x18\n \x01(\r\x12\x14\n\x0cmptcp_option\x18\x0b \x03(\x0c\"%\n\x12ReassembledPayload\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PACKETMSG = _descriptor.Descriptor(
  name='PacketMsg',
  full_name='seg_xfer.PacketMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='seg_xfer.PacketMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_ip', full_name='seg_xfer.PacketMsg.src_ip', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='seg_xfer.PacketMsg.src_port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dst_ip', full_name='seg_xfer.PacketMsg.dst_ip', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='seg_xfer.PacketMsg.dst_port', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tcp_flags', full_name='seg_xfer.PacketMsg.tcp_flags', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqno', full_name='seg_xfer.PacketMsg.seqno', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ackno', full_name='seg_xfer.PacketMsg.ackno', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='seg_xfer.PacketMsg.payload', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dsize', full_name='seg_xfer.PacketMsg.dsize', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mptcp_option', full_name='seg_xfer.PacketMsg.mptcp_option', index=10,
      number=11, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=225,
)


_REASSEMBLEDPAYLOAD = _descriptor.Descriptor(
  name='ReassembledPayload',
  full_name='seg_xfer.ReassembledPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='seg_xfer.ReassembledPayload.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=264,
)

DESCRIPTOR.message_types_by_name['PacketMsg'] = _PACKETMSG
DESCRIPTOR.message_types_by_name['ReassembledPayload'] = _REASSEMBLEDPAYLOAD

PacketMsg = _reflection.GeneratedProtocolMessageType('PacketMsg', (_message.Message,), dict(
  DESCRIPTOR = _PACKETMSG,
  __module__ = 'seg_xfer_pb2'
  # @@protoc_insertion_point(class_scope:seg_xfer.PacketMsg)
  ))
_sym_db.RegisterMessage(PacketMsg)

ReassembledPayload = _reflection.GeneratedProtocolMessageType('ReassembledPayload', (_message.Message,), dict(
  DESCRIPTOR = _REASSEMBLEDPAYLOAD,
  __module__ = 'seg_xfer_pb2'
  # @@protoc_insertion_point(class_scope:seg_xfer.ReassembledPayload)
  ))
_sym_db.RegisterMessage(ReassembledPayload)


# @@protoc_insertion_point(module_scope)
